const MINUTES_PER_PLAYER = 20;
const PLAYERS = 4;
const SECONDS_TO_ADD = 5;
const MIN_TURN_DURATION_TO_GIVE_BONUS_SECONDS = 2;

export { MINUTES_PER_PLAYER, PLAYERS, SECONDS_TO_ADD, MIN_TURN_DURATION_TO_GIVE_BONUS_SECONDS };